require:
  - rubocop-rails
  - rubocop-rspec

AllCops:
  NewCops: enable

Layout/LineLength:
  Enabled: true
  Max: 120
  AutoCorrect: true
  IgnoredPatterns: ['(\A|\s)#'] # не проверять комментарии. Особенно полезно для аннотаций в моделях.

RSpec/ExampleLength:
  Enabled: true
  Max: 30

Metrics/BlockLength:
  Enabled: true
  Max: 50
  IgnoredMethods:
    - configure
    - describe

Style/FrozenStringLiteralComment:
  Enabled: true

Style/Documentation:
  Enabled: false

RSpec/NotToNot:
  Enabled: false

RSpec/LetSetup:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

Naming/VariableNumber:
  Enabled: false

RSpec/ContextWording:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  Enabled: false

Style/RedundantPercentQ:
  Enabled: true
  Exclude:
    - 'spec/features/citizens/index_spec.rb'
